version: "3.8"

services:
  # API Gateway Service
  api-gateway:
    build:
      context: ./apiGateway
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./apiGateway:/app
    environment:
      - PORT=4000
      - AUTH_SERVICE_URL=http://auth:5000
      - POST_SERVICE_URL=http://post:5001
    networks:
      - app-network

  # Authentication Service
  auth:
    build:
      context: ./server/auth-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./server/auth-service:/app
    environment:
      - MONGO_URI=mongodb+srv://hishammpsn:y7SIwtwzl8kZXqPu@cluster0.euxsp.mongodb.net/auth_db?retryWrites=true&w=majority
      - SECRET=secret
      - PORT=5000
      - RABBITMQ_URL=amqp://rabbitmq:5672
    networks:
      - app-network
    depends_on:
      - rabbitmq 

  # Post Service
  post:
    build:
      context: ./server/post-service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./server/post-service:/app
    environment:
      - MONGO_URI=mongodb+srv://hishammpsn:y7SIwtwzl8kZXqPu@cluster0.euxsp.mongodb.net/post_db?retryWrites=true&w=majority
      - PORT=5001
      - ANALYTICAL_SERVICE_URL=analytical-service:40000
    networks:
      - app-network

  # RabbitMQ Service
  rabbitmq:
    image: rabbitmq:3-management
    hostname: my-rabbit
    ports:
      - "15672:15672"  # Management UI
      - "5672:5672"    # RabbitMQ protocol
    container_name: rabbitmq-container
    restart: unless-stopped
    networks:
      - app-network

  # Notification Service
  notification-service:
    build:
      context: ./server/email-service
      dockerfile: Dockerfile
    ports:
      - "6000:6000"  
    volumes:
      - ./server/email-service:/app
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672 
      - EMAIL_ID=hishammpsn@gmail.com  
      - PASS_KEY=ghmxhowpegsdumkf 
    networks:
      - app-network
    depends_on:
      - rabbitmq  

  analytical-service:
    build:
      context: ./server/analytical-service
      dockerfile: Dockerfile
    ports:
      - "40000:40000"  # gRPC server port
    volumes:
      - ./server/analytical-service:/usr/src/app
    environment:
      - MONGO_URI=mongodb+srv://hishammpsn:y7SIwtwzl8kZXqPu@cluster0.euxsp.mongodb.net/analytical_db?retryWrites=true&w=majority
      - PORT=5002
    networks:
      - app-network
    depends_on:
      - rabbitmq
      - post 
      

networks:
  app-network:
    driver: bridge
