apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  MONGO_URI: mongodb+srv://hishammpsn:y7SIwtwzl8kZXqPu@cluster0.euxsp.mongodb.net/auth_db?retryWrites=true&w=majority
  EMAIL_ID: aGlzaGFtbXBzbkBnbWFpbC5jb20=
  PASS_KEY: Z2hteGhvd3BlZ3NkdW1rZg==
