name: Build and Push Docker Images

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Registry
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and Push API Gateway Image
      - name: Build and Push API Gateway Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/memories-api_gateway-service:latest ./apiGateway
          docker push ${{ secrets.DOCKER_USERNAME }}/memories-api_gateway-service:latest

      # Step 4: Build and Push Authentication Service Image
      - name: Build and Push Auth Service Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/memories-auth-service:latest ./server/auth-service
          docker push ${{ secrets.DOCKER_USERNAME }}/memories-auth-service:latest

      # Step 5: Build and Push Post Service Image
      - name: Build and Push Post Service Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/memories-post-service:latest ./server/post-service
          docker push ${{ secrets.DOCKER_USERNAME }}/memories-post-service:latest

      # Step 6: Build and Push Notification Service Image
      - name: Build and Push Notification Service Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/memories-email-service:latest ./server/email-service
          docker push ${{ secrets.DOCKER_USERNAME }}/memories-email-service:latest
