name: Build and Push Docker Images

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [apiGateway, auth-service, post-service, email-service]
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Registry
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and Push Docker Images
      - name: Build and Push ${{ matrix.service }} Image
        uses: docker/build-push-action@v3
        with:
          context: ./server/${{ matrix.service }}
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/memories-${{ matrix.service }}:latest
